services:
  redis:
    image: redis:latest
    ports:
      - "16379:6379"

  shuttle_start:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run start
    env_file:
      - .env
    depends_on:
      - redis

  shuttle_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run worker
    env_file:
      - .env
    depends_on:
      - redis

  shuttle_backfill:
    build:
      context: .
      dockerfile: Dockerfile
    command: bun run backfill
    env_file:
      - .env
    depends_on:
      - redis